#!/bin/bash
# chkconfig: 234 20 80

# Source function library.
. /etc/init.d/functions

NAME="My Application Beta"
SOURCE_DIR=/sites/betas/my-application
SOURCE_FILE=app.js

PIDFILE=$SOURCE_DIR/pids/pid.pid

start() {


  if [ -f $PIDFILE ]; then
    echo -ne "$NAME already running\n"
    RETVAL=0
  else
    echo -ne 'Starting... \t\t\t\t\t[  \033[32mOK\033[0m  ]\n'
    daemon --user=root \
    nohup /usr/bin/node $SOURCE_DIR/$SOURCE_FILE > $SOURCE_DIR/output.log 2>&1 &
    RETVAL=$?
  fi
}

stop() {
  if [ -f $PIDFILE ]; then
    kill `cat $PIDFILE`
    rm -f $PIDFILE
    echo -ne 'Stopping... \t\t\t\t\t[  \033[32mOK\033[0m  ]\n'
  else
    echo -ne "$NAME is not running\n";
  fi
  RETVAL=$?
}

status() {
  if [ -f $PIDFILE ]; then
    echo -ne "$NAME is running\n"
  else
    echo -ne "$NAME is not running\n";
  fi
  RETVAL=$?
}

restart() {
  stop
  start
}

deploy() {
  cd $SOURCE_DIR && nohup git pull > output.log 2>&1 &
  echo -ne 'Git Pull... \t\t\t\t\t[  \033[32mOK\033[0m  ]\n'
  restart
}

 case "$1" in
    start)
        start
        ;;
    stop)
        stop
        ;;
    status)
        status
        ;;
    restart)
        restart
        ;;
    deploy)
        deploy
        ;;
    *)
        echo -ne "Usage: {start|stop|status|restart}\n"
        exit 1
        ;;
esac
exit $RETVAL